In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
path = "algebra_2006_2007_train.txt"
df = pd.read_table(path, encoding="ISO-8859-15", low_memory=False)
df.shape

(2270384, 19)

In [3]:
df.columns

Index(['Row', 'Anon Student Id', 'Problem Hierarchy', 'Problem Name',
       'Problem View', 'Step Name', 'Step Start Time',
       'First Transaction Time', 'Correct Transaction Time', 'Step End Time',
       'Step Duration (sec)', 'Correct Step Duration (sec)',
       'Error Step Duration (sec)', 'Correct First Attempt', 'Incorrects',
       'Hints', 'Corrects', 'KC(Default)', 'Opportunity(Default)'],
      dtype='object')

In [3]:

df.dropna(subset=['Problem Name', 'KC(Default)', 'Step Duration (sec)', 'Step Duration (sec)'], inplace=True)
df

,Row,Anon Student Id,Problem Hierarchy,Problem Name,Problem View,Step Name,Step Start Time,First Transaction Time,Correct Transaction Time,Step End Time,Step Duration (sec),Correct Step Duration (sec),Error Step Duration (sec),Correct First Attempt,Incorrects,Hints,Corrects,KC(Default),Opportunity(Default)
2,3,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,1,R2C1,2006-10-26 09:53:41.0,2006-10-26 09:53:46.0,2006-10-26 09:53:46.0,2006-10-26 09:53:46.0,5.0,5.0,NaN,1,0,0,1,Identifying units,1
3,4,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,1,R2C2,2006-10-26 09:53:46.0,2006-10-26 09:53:50.0,2006-10-26 09:53:50.0,2006-10-26 09:53:50.0,4.0,4.0,NaN,1,0,0,1,Identifying units,2
4,5,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,1,R4C1,2006-10-26 09:53:50.0,2006-10-26 09:54:05.0,2006-10-26 09:54:05.0,2006-10-26 09:54:05.0,15.0,15.0,NaN,1,0,0,1,Entering a given,1
5,6,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,1,R4C2,2006-10-26 09:54:05.0,2006-10-26 09:54:20.0,2006-10-26 09:54:41.0,2006-10-26 09:54:41.0,36.0,NaN,36.0,0,2,0,1,"Find Y, any form",1
6,7,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,1,R5C1,2006-10-26 09:54:41.0,2006-10-26 09:54:57.0,2006-10-26 09:54:57.0,2006-10-26 09:54:57.0,16.0,16.0,NaN,1,0,0,1,Entering a given,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2270377,3025927,248ck2dj1,"Unit ROOTS, Section ROOTS-1",ROOTS1-001,1,NegativeResult,2007-03-08 14:07:04.0,2007-03-08 14:07:05.0,2007-03-08 14:07:05.0,2007-03-08 14:07:05.0,1.0,1.0,NaN,1,0,0,1,Write given square as whole number,2
2270378,3025928,248ck2dj1,"Unit ROOTS, Section ROOTS-1",ROOTS1-001,1,PositiveRoot,2007-03-08 14:07:05.0,2007-03-08 14:07:11.0,2007-03-08 14:07:11.0,2007-03-08 14:07:11.0,6.0,6.0,NaN,1,0,0,1,Find positive square root,1
2270379,3025929,248ck2dj1,"Unit ROOTS, Section ROOTS-1",ROOTS1-001,1,NegativeRoot,2007-03-08 14:07:11.0,2007-03-08 14:07:14.0,2007-03-08 14:07:14.0,2007-03-08 14:07:14.0,3.0,3.0,NaN,1,0,0,1,Find negative square root,1
2270380,3025930,248ck2dj1,"Unit ROOTS, Section ROOTS-1",ROOTS1-008,1,NumberLine,2007-03-08 14:07:21.0,2007-03-08 14:07:35.0,2007-03-08 14:07:35.0,2007-03-08 14:07:35.0,14.0,14.0,NaN,1,0,0,1,Construct square from side length,1
2270383,3025933,248ck2dj1,"Unit ROOTS, Section ROOTS-1",ROOTS1-008,1,PositiveResult,2007-03-08 14:07:47.0,2007-03-08 14:07:49.0,2007-03-08 14:07:49.0,2007-03-08 14:07:49.0,2.0,2.0,NaN,1,0,0,1,Write given whole number as square,1

In [37]:
key_user, key_qtype, key_q, key_s, key_elpsed, key_correct = 'Anon Student Id', 'Problem Hierarchy', 'Problem Name', 'KC(Default)', 'Step Duration (sec)', 'Correct First Attempt'
columns = [key_user, key_qtype, key_q, key_s, key_elpsed, key_correct]
df1 = df[[key_user, key_qtype, key_q, key_s, key_elpsed, key_correct]]
df1.head()

,Anon Student Id,Problem Hierarchy,Problem Name,KC(Default),Step Duration (sec),Correct First Attempt
2,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,Identifying units,5.0,1
3,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,Identifying units,4.0,1
4,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,Entering a given,15.0,1
5,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,"Find Y, any form",36.0,0
6,JG4Tz,"Unit CTA1_01, Section CTA1_01-1",LDEMO_WKST,Entering a given,16.0,1

### algbra interaction

In [38]:
len(df1)

1806782

In [39]:
question_id_dict = dict(zip(df[key_q].unique(), range(len(df[key_q].unique()))))
question_type_dict = dict(zip(df[key_qtype].unique(), range(len(df[key_qtype].unique()))))
user_id_dict = dict(zip(df[key_user].unique(), range(len(df[key_user].unique()))))
skill_id_dict = dict(zip(df[key_s].unique(), range(len(df[key_s].unique()))))

df1[key_q] = df1[key_q].map(question_id_dict)
df1[key_s] = df1[key_s].map(skill_id_dict)
df1[key_qtype] = df1[key_qtype].map(question_type_dict)

N_QUESTION = len(question_id_dict)
N_SKILL = len(skill_id_dict)
N_QUESTION_TYPE = len(question_type_dict)
N_USER = len(user_id_dict)

print("N_USER:{}, N_QUESTION:{}, N_SKILL:{}, N_QUESTION_TYPE:{}".format(N_USER, N_QUESTION, N_SKILL, N_QUESTION_TYPE))

N_USER:1336, N_QUESTION:91759, N_SKILL:1703, N_QUESTION_TYPE:153

In [40]:
key_qd = 'diff'

group1 = df1[[key_q, key_correct]].groupby([key_q]).apply(lambda r:r[key_correct].sum() / len(r[key_correct]))
group1
df1[key_qd] = df1[key_q].map(group1)
df1.head()

,Anon Student Id,Problem Hierarchy,Problem Name,KC(Default),Step Duration (sec),Correct First Attempt,diff
2,JG4Tz,0,0,0,5.0,1,0.685914
3,JG4Tz,0,0,0,4.0,1,0.685914
4,JG4Tz,0,0,1,15.0,1,0.685914
5,JG4Tz,0,0,2,36.0,0,0.685914
6,JG4Tz,0,0,1,16.0,1,0.685914

In [41]:
# 我们需要将数据进行预处理，每个学生的学习记录利用group by合并为序列。
group = df1.groupby([key_user]).apply(lambda r: (
            r[key_q].values,
            r[key_s].values,
            r[key_qtype].values,
            r[key_qd].values,
            r[key_elpsed].values,
            r[key_correct].values
            ))

In [42]:
print(len(group))

1336

In [43]:
df1.to_csv("data.csv", index=None)

In [44]:
from tqdm import tqdm
from sklearn.model_selection import train_test_split

In [45]:
from tqdm import tqdm
from sklearn.model_selection import train_test_split

train, test = train_test_split(group, test_size=0.2, random_state=42)

def generate_df_by_group(group):
    df = pd.DataFrame(columns=['user_id', 'q_idx', 's_idx', 'q_type', 'q_diff', 'ms_first_response', 'correct'])
    for user_id, (q, s, qt, qd, ms_first_response, correct) in tqdm(group.items()):
        for i in range(len(q)):
            tmp = [user_id, q[i], s[i], qt[i], qd[i], ms_first_response[i], correct[i]]
            df.loc[len(df)] = tmp
    return df
print(len(train), len(test))

1068 268

In [32]:
df_train = generate_df_by_group(train)
df_test = generate_df_by_group(test)

24it [01:58,  4.94s/it]

KeyboardInterrupt:

In [46]:
df_train

              user_id  q_idx s_idx q_type    q_diff  ms_first_response correct
0        271qgzl01euj  13359    10      7  0.883450              388.0       1
1        271qgzl01euj  13359    11      7  0.883450               23.0       1
2        271qgzl01euj  29143    12      7  0.857143               97.0       0
3        271qgzl01euj  29143    13      7  0.857143                9.0       1
4        271qgzl01euj  29144    12      7  1.000000               12.0       1
...               ...    ...   ...    ...       ...                ...     ...
1406474  271rvw8pyrgs  29370    10     11  1.000000                5.0       1
1406475  271rvw8pyrgs  29370    21     11  1.000000                8.0       1
1406476  271rvw8pyrgs  29370    12     11  1.000000                6.0       1
1406477  271rvw8pyrgs  29370    18     11  1.000000                6.0       1
1406478  271rvw8pyrgs  29371    11     11  1.000000                6.0       1

[1406479 rows x 7 columns]

In [50]:
df_train.columns

Index(['user_id', 'q_idx', 's_idx', 'q_type', 'q_diff', 'ms_first_response',
       'correct'],
      dtype='object')

In [51]:
from sklearn.preprocessing import MinMaxScaler

sacler = MinMaxScaler()

col = ['ms_first_response']
tmp = sacler.fit_transform(df_train[col])
df_train[col] = tmp

tmp = sacler.transform(df_test[col])
df_test[col] = tmp

In [52]:
# from sklearn.preprocessing import MinMaxScaler

# sacler = MinMaxScaler()

# col = [key_elpsed]
# tmp = sacler.fit_transform(df_train[col])
# df_train[col] = tmp

# tmp = sacler.transform(df_test[col])
# df_test[col] = tmp

In [ ]:
df_train.to_csv("train.csv", index=None)
df_test.to_csv("test.csv", index=None)